displayName=Pet Growth Tracker
author=DV8FromTheWorld
support=https://github.com/DV8FromTheWorld/runelite-pet-growth-tracker
description=Tracks the growth and hunger of your kitten/cat or puppy/dog, and warns you before it runs away or stops growing
tags=kitten,cat,puppy,dog,pet,growth,hunger,status,alert
plugins=net.dv8tion.runelite.petgrowthtracker.PetTrackerPlugin
build=standard
